export const ADD_CONVERSATION = "ADD_CONVERSATION";
export const DELETE_CONVERSATION = "DELETE_CONVERSATION";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_CONVERSATION = "UPDATE_CONVERSATION";
export const FILTER_CONVERSATIONS = "FILTER_CONVERSATIONS";
export const CLEAR_FILTER = "CLEAR_FILTER";
