#docker-compose.yml file for Caddy and Client Image

version: "3.8"

services:
   react-app:
      image: client-image:latest
      container_name: react-app
      ports:
         - "3000:3000"
      restart: unless-stopped
      stdin_open: true
      tty: true

   caddy:
      image: caddy:latest
      container_name: caddy
      restart: unless-stopped
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./Caddyfile:/etc/caddy/Caddyfile
      depends_on:
         - react-app
