version: "3.8"

networks:
   chat-network:
      driver: bridge

services:
   zookeeper:
      image: wurstmeister/zookeeper
      container_name: zookeeper
      ports:
         - "2181:2181"
      network_mode: bridge
      #all services should running on bridge network

   kafka:
      image: wurstmeister/kafka
      container_name: kafka
      ports:
         - "9092:9092"
      environment:
         KAFKA_ZOOKEEPER_CONNECT: 172.17.0.1:2181
         KAFKA_CREATE_TOPICS: messages:1:1
         KAFKA_LISTENERS: OUTSIDE://0.0.0.0:9092
         KAFKA_ADVERTISED_LISTENERS: OUTSIDE://44.201.100.80:9092
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT
         KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
         KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      depends_on:
         - zookeeper
      network_mode: bridge

   postgres:
      image: postgres
      container_name: postgres
      ports:
         - "5432:5432"
      environment:
         POSTGRES_DB: chat-app
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: AndrewLuck626!
      #note: this was change from C:\pg_volume: following setting up of ec2 instance
      volumes:
         - postgres_data:/var/lib/postgresql/data
      restart: always
      network_mode: bridge

   spring-boot-app:
      image: api-image:latest
      container_name: spring-boot-app
      ports:
         - "8080:8080"
      depends_on:
         - zookeeper
         - kafka
         - postgres
      restart: always
      network_mode: bridge
#    react-app:
#       image: client-image:latest
#       container_name: react-client-container
#       ports:
#          - "3000:3000"
#       stdin_open: true
#       tty: true
#       network_mode: bridge
#       depends_on:
#          - zookeeper
#          - postgres
#          - kafka
#          - spring-boot-app
volumes:
   postgres_data:
